### ISSUE TITLE
 What is resnet18_25db.txt

### ISSUE THREAD

**Issue by lh812** [maybeliuchuan/Task-Oriented-Semantic-Communications#1]

**Comment by maybeliuchuan** [comment]
This file is the semantic importance file obtained via the variable "weights" in “ResNet18_CAM.py”. The classification task-oriented semantic communication model we considered is based on Resnet18 and trained when the SNR equals to 25 dB. You can change it to yours according the model you used.

**Comment by lh812** [comment]
Thanks for your reply! How to train to get semantic importance files, can you tell me the steps

**Comment by maybeliuchuan** [comment]
The details of training can be found in “MI+Classification_resnet.py”. Once obtained the trained sc model, you can use “ResNet18_CAM.py” to calculate the semantic importance weights of different features.
